---
- name: Deploy ClickHouse Cluster
  hosts: clickhouse_cluster
  become: true
  vars:
    # ClickHouse Configuration
    clickhouse_version: "25.8.1.5101"
    clickhouse_cluster_name: "production_cluster"

    # Enable components
    keeper_enabled: true
    haproxy_enabled: true
    keepalived_enabled: true # Set to true for HA setup
    tls_enabled: false # Set to true for SSL/TLS

    # Network Configuration
    clickhouse_http_port: 8123
    clickhouse_tcp_port: 9000

    # HAProxy Configuration
    haproxy_stats_port: 8404
    haproxy_frontend_http_port: 8124
    haproxy_frontend_tcp_port: 9001

    # Keepalived Configuration (if enabled)
    keepalived_virtual_ip: "192.168.23.20"
    keepalived_interface: "eth0"

    # Resource Limits
    clickhouse_max_memory_usage: "6GB"
    clickhouse_max_concurrent_queries: 200

  roles:
    - vasyansk.clickhouse_cluster

  post_tasks:
    - name: Wait for ClickHouse to be ready
      uri:
        url: "http://localhost:{{ clickhouse_http_port }}/ping"
        method: GET
      register: result
      until: result.status == 200
      retries: 5
      delay: 10

    - name: Display ClickHouse status
      debug:
        msg: "ClickHouse is running on {{ ansible_default_ipv4['address'] }}:{{ clickhouse_http_port }}"

    - name: Display HAProxy stats URL
      debug:
        msg: "HAProxy stats available at http://{{ ansible_default_ipv4['address'] }}:{{ haproxy_stats_port }}/stats"
      when: haproxy_enabled
