---
# ClickHouse installation and configuration tasks

- name: Add ClickHouse repository
  block:
    - name: Install prerequisite packages for Debian/Ubuntu
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        update_cache: yes
        state: present
      when: ansible_os_family == "Debian"

    - name: Download ClickHouse GPG key and store in keyring
      shell: |
        curl -fsSL 'https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key' | gpg --dearmor -o /usr/share/keyrings/clickhouse-keyring.gpg
      args:
        creates: /usr/share/keyrings/clickhouse-keyring.gpg
      when: ansible_os_family == "Debian"

    - name: Get system architecture
      shell: dpkg --print-architecture
      register: system_arch
      when: ansible_os_family == "Debian"

    - name: Add ClickHouse repository to apt sources
      lineinfile:
        path: /etc/apt/sources.list.d/clickhouse.list
        line: "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg arch={{ system_arch.stdout }}] https://packages.clickhouse.com/deb stable main"
        create: yes
        state: present
      when: ansible_os_family == "Debian"

    - name: Update apt package lists
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add ClickHouse repository for RHEL/CentOS
      yum_repository:
        name: clickhouse
        description: ClickHouse Repository
        baseurl: https://packages.clickhouse.com/rpm/stable/x86_64/
        gpgcheck: yes
        gpgkey: https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key
        enabled: yes
      when: ansible_os_family == "RedHat"

- name: Install ClickHouse packages
  package:
    name:
      - "{{ 'clickhouse-server=' + clickhouse_version if clickhouse_version != 'latest' else 'clickhouse-server' }}"
      - "{{ 'clickhouse-client=' + clickhouse_version if clickhouse_version != 'latest' else 'clickhouse-client' }}"
    state: present

- name: Create ClickHouse directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: "0755"
  loop:
    - "{{ clickhouse_data_dir }}"
    - "{{ clickhouse_log_dir }}"
    - "{{ clickhouse_config_dir }}"

- name: Convert memory usage to bytes
  set_fact:
    clickhouse_max_memory_usage_bytes: "{{ (clickhouse_max_memory_usage | regex_replace('GB', '') | int) * 1073741824 }}"
  when: clickhouse_max_memory_usage is match('.*GB.*')

- name: Configure ClickHouse server
  template:
    src: clickhouse-config.xml.j2
    dest: "{{ clickhouse_config_dir }}/config.xml"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: "0644"

- name: Configure ClickHouse users
  template:
    src: users.xml.j2
    dest: "{{ clickhouse_config_dir }}/users.xml"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: "0644"

- name: Start ClickHouse service
  service:
    name: clickhouse-server
    state: started
    enabled: yes
